

ROLES = {
    'angler': {
        'vocabulary':{
            'stock': 'bait and tackle',
            'wares': 'nets and hooks',
            'inventory': 'fishing gear',
            'browse': 'check the nets',
            'look': 'eye the traps',
            'examine': 'inspect the lines',
            'need': 'hookin',
            'require': 'baitin',
            'help': 'a cast',
            'assistance': 'a line',
            'interesting': 'big one',
            'prime': 'monster catch',
            'rare': 'legendary fish',
            'place': 'fishin hole',
            'market': 'best tide',
            'area': 'deep drop',
            'work': 'haulin nets',
            'working': 'castin lines',
            'trade': 'swap catches',
            'deal': 'fresh haul',
            'cargo': 'barrels of fish',
            'provisions': 'salted cod',
            'safe': 'no sharks',
            'come back': 'when the tide’s right',
            'see you': 'next full moon',
            'water': 'brine',
            'sea': 'the drink',
            'storm': 'blow',
            'wind': 'breeze off the reef',
            'island': 'atoll',
            'ship': 'skiff',
            'crew': 'deckhand',
            'you': 'cap’n',
            'we': 'the crew'
        }
    },
    'miner': {
        'vocabulary':{
            'stock': 'picks and chisels',
            'wares': 'ore samples',
            'inventory': 'raw gems',
            'browse': 'sort the stones',
            'look': 'scan the haul',
            'examine': 'grade the rocks',
            'need': 'diggin',
            'require': 'blastin',
            'help': 'a vein',
            'assistance': 'a strike',
            'interesting': 'motherlode',
            'prime': 'high-grade seam',
            'rare': 'blood diamond',
            'place': 'quarry face',
            'market': 'refinery',
            'area': 'crater ridge',
            'work': 'breakin rock',
            'working': 'hammerin stone',
            'trade': 'swap nuggets',
            'deal': 'raw ore',
            'cargo': 'sacks of quartz',
            'provisions': 'lantern oil',
            'safe': 'no cave-ins',
            'come back': 'after the next blast',
            'see you': 'when the dust settles',
            'water': 'underground spring',
            'sea': 'dry dock',
            'storm': 'rockslide',
            'wind': 'tunnel draft',
            'island': 'volcanic peak',
            'ship': 'cargo hauler',
            'crew': 'miner',
            'you': 'foreman',
            'we': 'the crew'
        }
    },
    'oarsman': {
        'vocabulary':{
            'stock': 'oars and tholes',
            'wares': 'sweat and muscle',
            'inventory': 'spare benches',
            'browse': 'check the stroke',
            'look': 'time the pull',
            'examine': 'feel the rhythm',
            'need': 'pullin',
            'require': 'rowin hard',
            'help': 'a stroke',
            'assistance': 'a beat',
            'interesting': 'strong current',
            'prime': 'tailwind run',
            'rare': 'perfect cadence',
            'place': 'open lane',
            'market': 'finish line',
            'area': 'smooth water',
            'work': 'haulin oar',
            'working': 'keepin time',
            'trade': 'swap shifts',
            'deal': 'faster passage',
            'cargo': 'light load',
            'provisions': 'water skins',
            'safe': 'no blisters',
            'come back': 'at the next tide',
            'see you': 'on the downbeat',
            'water': 'channel',
            'sea': 'the race',
            'storm': 'headwind',
            'wind': 'following breeze',
            'island': 'lee shore',
            'ship': 'longboat',
            'crew': 'rower',
            'you': 'coxswain',
            'we': 'the bench'
        }
    },
    'trader': {
        'vocabulary':{
            'stock': 'cargo manifest',
            'wares': 'trade goods',
            'inventory': 'market rates',
            'browse': 'review the ledger',
            'look': 'check the margins',
            'examine': 'audit the books',
            'need': 'negotiate',
            'require': 'counter-offer',
            'help': 'a bargain',
            'assistance': 'a deal',
            'interesting': 'hot commodity',
            'prime': 'bull market',
            'rare': 'exclusive contract',
            'place': 'best market',
            'market': 'trading post',
            'area': 'port of call',
            'work': 'makin deals',
            'working': 'closing sales',
            'trade': 'barter',
            'deal': 'final price',
            'cargo': 'hold full',
            'provisions': 'luxury items',
            'safe': 'no tariffs',
            'come back': 'when prices rise',
            'see you': 'at the exchange',
            'water': 'shipping lane',
            'sea': 'trade winds',
            'storm': 'market crash',
            'wind': 'favorable rates',
            'island': 'free port',
            'ship': 'merchantman',
            'crew': 'factor',
            'you': 'buyer',
            'we': 'the house'
        }
    },
    'carpenter': {
        'vocabulary':{
            'stock': 'planks and caulk',
            'wares': 'timber and tar',
            'inventory': 'spare beams',
            'browse': 'check the grain',
            'look': 'eye the damage',
            'examine': 'measure the breach',
            'need': 'patchin',
            'require': 'caulkin',
            'help': 'a mend',
            'assistance': 'a brace',
            'interesting': 'critical leak',
            'prime': 'solid oak',
            'rare': 'ironwood patch',
            'place': 'dry dock',
            'market': 'shipyard',
            'area': 'below waterline',
            'work': 'hammerin nails',
            'working': 'sawing planks',
            'trade': 'swap lumber',
            'deal': 'repair contract',
            'cargo': 'ballast stone',
            'provisions': 'pitch and oakum',
            'safe': 'no splinters',
            'come back': 'after the swell',
            'see you': 'when she’s tight again',
            'water': 'bilge',
            'sea': 'the frame',
            'storm': 'taking on water',
            'wind': 'creaking mast',
            'island': 'timber caye',
            'ship': 'hull',
            'crew': 'chipper',
            'you': 'captain',
            'we': 'the yard'
        }
    },
    'navigator': {
        'vocabulary':{
            'stock': 'charts and sextants',
            'wares': 'star maps',
            'inventory': 'logbooks',
            'browse': 'plot the course',
            'look': 'take a bearing',
            'examine': 'read the stars',
            'need': 'a heading',
            'require': 'true north',
            'help': 'a fix',
            'assistance': 'a position',
            'interesting': 'uncharted waters',
            'prime': 'perfect meridian',
            'rare': 'ley line',
            'place': 'true north',
            'market': 'cartographer’s guild',
            'area': 'open ocean',
            'work': 'plotting course',
            'working': 'shooting the sun',
            'trade': 'swap bearings',
            'deal': 'secret route',
            'cargo': 'blank charts',
            'provisions': 'ink and quills',
            'safe': 'no fog',
            'come back': 'at high noon',
            'see you': 'under the same stars',
            'water': 'latitude',
            'sea': 'the grid',
            'storm': 'magnetic deviation',
            'wind': 'prevailing current',
            'island': 'uncharted isle',
            'ship': 'vessel',
            'crew': 'quartermaster',
            'you': 'captain',
            'we': 'the watch'
        }
    },
    'surgeon': {
        'vocabulary':{
            'stock': 'bandages and salves',
            'wares': 'herbs and rum',
            'inventory': 'medical kit',
            'browse': 'check the wounds',
            'look': 'take a pulse',
            'examine': 'diagnose',
            'need': 'stitchin',
            'require': 'amputatin',
            'help': 'a poultice',
            'assistance': 'a dose',
            'interesting': 'plague outbreak',
            'prime': 'miracle cure',
            'rare': 'fountain herb',
            'place': 'sick bay',
            'market': 'apothecary',
            'area': 'below deck',
            'work': 'tendin wounds',
            'working': 'boilin instruments',
            'trade': 'swap remedies',
            'deal': 'health contract',
            'cargo': 'medical crates',
            'provisions': 'laudanum',
            'safe': 'no infection',
            'come back': 'after the fever breaks',
            'see you': 'when you’re whole',
            'water': 'blood',
            'sea': 'the fever',
            'storm': 'outbreak',
            'wind': 'plague wind',
            'island': 'leper colony',
            'ship': 'hospital ship',
            'crew': 'patient',
            'you': 'captain',
            'we': 'the orderlies'
        }
    },
    'cook': {
        'vocabulary':{
            'stock': 'hard tack and salt pork',
            'wares': 'stew and grog',
            'inventory': 'spice rack',
            'browse': 'sample the pot',
            'look': 'check the fire',
            'examine': 'taste the broth',
            'need': 'cookin',
            'require': 'servin',
            'help': 'a ladle',
            'assistance': 'a portion',
            'interesting': 'fresh catch',
            'prime': 'five-star meal',
            'rare': 'kraken steak',
            'place': 'galley stove',
            'market': 'mess deck',
            'area': 'below deck',
            'work': 'stirrin pots',
            'working': 'peelin spuds',
            'trade': 'swap recipes',
            'deal': 'full belly',
            'cargo': 'provision crates',
            'provisions': 'fresh bread',
            'safe': 'no weevils',
            'come back': 'at mess call',
            'see you': 'when the bell rings',
            'water': 'broth',
            'sea': 'the slush',
            'storm': 'spoiled rations',
            'wind': 'kitchen draft',
            'island': 'spice atoll',
            'ship': 'galley',
            'crew': 'messmate',
            'you': 'captain',
            'we': 'the scullery'
        }
    }
}
