
ARCHETYPES = {
    'pirate': {
        'vocabulary':{
            'welcome': 'ahoy',
            'hello': 'ahoy',
            'you': 'ye',
            'your': 'yer',
            'our': 'me',
            'are': 'be',
            'is': 'be',
            'browse': 'eyeball',
            'look': 'gander',
            'stock': 'wares',
            'prices': 'prices',
            'marked': 'carved in stone',
            'need': 'be needin',
            'help': 'lend a hand',
            'goodbye': 'fare thee well',
            'thanks': 'much obliged',
            'please': 'if ye please',
            'yes': 'aye',
            'no': 'nay',
            'question': 'query',
            'interested': 'keen',
            'deal': 'bargain',
            'trade': 'swap',
            'safe': 'fair winds',
            'come back': 'return to port',
            'see you': 'catch ye on the tide'
        }
    },
    'colonial': {
        'vocabulary':{
            'welcome': 'good day',
            'hello': 'greetings',
            'you': 'sir',
            'your': 'your',
            'our': 'our',
            'we': 'we',
            'are': 'are',
            'is': 'is',
            'browse': 'peruse',
            'look': 'examine',
            'stock': 'inventory',
            'prices': 'rates',
            'marked': 'listed',
            'need': 'require',
            'help': 'assistance',
            'goodbye': 'farewell',
            'thanks': 'my thanks',
            'please': 'if you please',
            'yes': 'indeed',
            'no': 'I decline',
            'question': 'inquiry',
            'interested': 'intrigued',
            'deal': 'arrangement',
            'trade': 'commerce',
            'safe': 'godspeed',
            'come back': 'return at your leisure',
            'see you': 'until we meet again'
        }
    },
    'smuggler': {
        'vocabulary':{
            'welcome': 'psst',
            'hello': 'oi',
            'you': 'mate',
            'your': 'yer',
            'our': 'our',
            'we': 'we',
            'are': 'are',
            'is': 'is',
            'browse': 'take a peek',
            'look': 'check',
            'stock': 'the goods',
            'prices': 'cost',
            'marked': 'final',
            'need': 'after',
            'help': 'a favor',
            'goodbye': 'keep it quiet',
            'thanks': 'owe ya',
            'please': 'c’mon',
            'yes': 'deal',
            'no': 'pass',
            'question': 'word',
            'interested': 'in',
            'deal': 'the job',
            'trade': 'swap',
            'safe': 'no trouble',
            'come back': 'next drop',
            'see you': 'later'
        }
    }
}
