
role_vocabularies:dict[str, dict] = {
    'fisher': {
        'stock': 'bait and tackle',
        'wares': 'nets and hooks',
        'inventory': 'fishing gear',
        'browse': 'check the nets',
        'look': 'eye the traps',
        'examine': 'inspect the lines',
        'need': 'hookin',
        'require': 'baitin',
        'help': 'a cast',
        'assistance': 'a line',
        'interesting': 'big one',
        'prime': 'monster catch',
        'rare': 'legendary',
        'place': 'fishin hole',
        'market': 'best tide',
        'area': 'deep drop',
        'work': 'haulin nets',
        'working': 'castin lines',
        'trade': 'swap catches',
        'deal': 'fresh haul',
        'cargo': 'barrels of fish',
        'provisions': 'salted cod',
        'safe': 'no sharks',
        'come back': 'when the tide’s right',
        'see you': 'next full moon',
        'water': 'brine',
        'sea': 'the drink',
        'storm': 'blow',
        'wind': 'breeze off the reef',
        'island': 'atoll',
        'ship': 'skiff',
        'crew': 'deckhand',
        'you': 'cap’n',
        'we': 'the crew'
    },
    'rockhound': {
        'stock': 'picks and chisels',
        'wares': 'ore samples',
        'inventory': 'raw gems',
        'browse': 'sort the stones',
        'look': 'scan the haul',
        'examine': 'grade the rocks',
        'need': 'diggin',
        'require': 'blastin',
        'help': 'a vein',
        'assistance': 'a strike',
        'interesting': 'motherlode',
        'prime': 'high-grade seam',
        'rare': 'blood diamond',
        'place': 'quarry face',
        'market': 'refinery',
        'area': 'crater ridge',
        'work': 'breakin rock',
        'working': 'hammerin stone',
        'trade': 'swap nuggets',
        'deal': 'raw ore',
        'cargo': 'sacks of quartz',
        'provisions': 'lantern oil',
        'safe': 'no cave-ins',
        'come back': 'after the next blast',
        'see you': 'when the dust settles',
        'water': 'underground spring',
        'sea': 'dry dock',
        'storm': 'rockslide',
        'wind': 'tunnel draft',
        'island': 'volcanic peak',
        'ship': 'cargo hauler',
        'crew': 'miner',
        'you': 'foreman',
        'we': 'the crew'
    },
    'deckhand': {
        'stock': 'oars and tholes',
        'wares': 'sweat and muscle',
        'inventory': 'spare benches',
        'browse': 'check the stroke',
        'look': 'time the pull',
        'examine': 'feel the rhythm',
        'need': 'pullin',
        'require': 'rowin hard',
        'help': 'a stroke',
        'assistance': 'a beat',
        'interesting': 'strong current',
        'prime': 'tailwind run',
        'rare': 'perfect cadence',
        'place': 'open lane',
        'market': 'finish line',
        'area': 'smooth water',
        'work': 'haulin oar',
        'working': 'keepin time',
        'trade': 'swap shifts',
        'deal': 'faster passage',
        'cargo': 'light load',
        'provisions': 'water skins',
        'safe': 'no blisters',
        'come back': 'at the next tide',
        'see you': 'on the downbeat',
        'water': 'channel',
        'sea': 'the race',
        'storm': 'headwind',
        'wind': 'following breeze',
        'island': 'lee shore',
        'ship': 'longboat',
        'crew': 'rower',
        'you': 'coxswain',
        'we': 'the bench'
    },
    'merchant': {
        'stock': 'cargo manifest',
        'wares': 'trade goods',
        'inventory': 'market rates',
        'browse': 'review the ledger',
        'look': 'check the margins',
        'examine': 'audit the books',
        'need': 'negotiate',
        'require': 'counter-offer',
        'help': 'a bargain',
        'assistance': 'a deal',
        'interesting': 'hot commodity',
        'prime': 'bull market',
        'rare': 'exclusive contract',
        'place': 'best market',
        'market': 'trading post',
        'area': 'port of call',
        'work': 'makin deals',
        'working': 'closing sales',
        'trade': 'barter',
        'deal': 'final price',
        'cargo': 'hold full',
        'provisions': 'luxury items',
        'safe': 'no tariffs',
        'come back': 'when prices rise',
        'see you': 'at the exchange',
        'water': 'shipping lane',
        'sea': 'trade winds',
        'storm': 'market crash',
        'wind': 'favorable rates',
        'island': 'free port',
        'ship': 'merchantman',
        'crew': 'factor',
        'you': 'buyer',
        'we': 'the house'
    },
    'artificer': {
        'stock': 'bandages and salves',
        'wares': 'herbs and rum',
        'inventory': 'medical kit',
        'browse': 'check the wounds',
        'look': 'take a pulse',
        'examine': 'diagnose',
        'need': 'stitchin',
        'require': 'amputatin',
        'help': 'a poultice',
        'assistance': 'a dose',
        'interesting': 'plague outbreak',
        'prime': 'miracle cure',
        'rare': 'fountain herb',
        'place': 'sick bay',
        'market': 'apothecary',
        'area': 'below deck',
        'work': 'tendin wounds',
        'working': 'boilin instruments',
        'trade': 'swap remedies',
        'deal': 'health contract',
        'cargo': 'medical crates',
        'provisions': 'laudanum',
        'safe': 'no infection',
        'come back': 'after the fever breaks',
        'see you': 'when you’re whole',
        'water': 'blood',
        'sea': 'the fever',
        'storm': 'outbreak',
        'wind': 'plague wind',
        'island': 'leper colony',
        'ship': 'hospital ship',
        'crew': 'patient',
        'you': 'captain',
        'we': 'the orderlies'
    },
    'islander': {
        'stock': 'casks and barrels',
        'wares': 'pressings and oils',
        'inventory': 'fermenting vats',
        'browse': 'check the casks',
        'look': 'eye the barrels',
        'examine': 'inspect the press',
        'need': 'tapin',
        'require': 'fermentin',
        'help': 'a draw',
        'assistance': 'a stir',
        'interesting': 'prime vintage',
        'prime': 'rare extract',
        'rare': 'legendary batch',
        'place': 'distillery',
        'market': 'trading post',
        'area': 'vineyard row',
        'work': 'pressin grapes',
        'working': 'stirrin vats',
        'trade': 'swap barrels',
        'deal': 'finished product',
        'cargo': 'kegs and casks',
        'provisions': 'clean water',
        'safe': 'no spills',
        'come back': 'after fermentation',
        'see you': 'at the next harvest',
        'water': 'clear draught',
        'sea': 'the vat',
        'storm': 'overflow',
        'wind': 'fermenting breeze',
        'island': 'vine-covered hill',
        'ship': 'press house',
        'crew': 'islander',
        'you': 'master of casks',
        'we': 'the cellar crew'
    },
    'operative': {
        'stock': 'coded messages',
        'wares': 'intel and secrets',
        'inventory': 'disguises and notes',
        'browse': 'review the reports',
        'look': 'observe the targets',
        'examine': 'scrutinize the situation',
        'need': 'gather info',
        'require': 'tail the mark',
        'help': 'a tip',
        'assistance': 'a lead',
        'interesting': 'suspicious activity',
        'prime': 'critical intel',
        'rare': 'classified info',
        'place': 'safe house',
        'market': 'informant network',
        'area': 'operating zone',
        'work': 'collect intelligence',
        'working': 'shadowing the target',
        'trade': 'exchange tips',
        'deal': 'covert arrangement',
        'cargo': 'secret parcels',
        'provisions': 'hidden supplies',
        'safe': 'undetected',
        'come back': 'after recon',
        'see you': 'at the rendezvous',
        'water': 'channels and couriers',
        'sea': 'information network',
        'storm': 'crisis',
        'wind': 'whispers',
        'island': 'hideout',
        'ship': 'disguised conveyance',
        'crew': 'operative',
        'you': 'handler',
        'we': 'the cell'
    },
}

archetype_vocabularies:dict[str, dict] = {
    'pirate': {
        'welcome': 'ahoy',
        'hello': 'ahoy',
        'you': 'ye',
        'your': 'yer',
        'our': 'me',
        'are': 'be',
        'is': 'be',
        'browse': 'eyeball',
        'look': 'gander',
        'stock': 'wares',
        'prices': 'prices',
        'marked': 'carved in stone',
        'need': 'be needin',
        'help': 'lend a hand',
        'goodbye': 'fare thee well',
        'thanks': 'much obliged',
        'please': 'if ye please',
        'yes': 'aye',
        'no': 'nay',
        'question': 'query',
        'interested': 'keen',
        'deal': 'bargain',
        'trade': 'swap',
        'safe': 'fair winds',
        'come back': 'return to port',
        'see you': 'catch ye on the tide'
    },
    'colonial': {
        'welcome': 'good day',
        'hello': 'greetings',
        'you': 'sir',
        'your': 'your',
        'our': 'our',
        'we': 'we',
        'are': 'are',
        'is': 'is',
        'browse': 'peruse',
        'look': 'examine',
        'stock': 'inventory',
        'prices': 'rates',
        'marked': 'listed',
        'need': 'require',
        'help': 'assistance',
        'goodbye': 'farewell',
        'thanks': 'my thanks',
        'please': 'if you please',
        'yes': 'indeed',
        'no': 'I decline',
        'question': 'inquiry',
        'interested': 'intrigued',
        'deal': 'arrangement',
        'trade': 'commerce',
        'safe': 'godspeed',
        'come back': 'return at your leisure',
        'see you': 'until we meet again'
    },
    'smuggler': {
        'welcome': 'psst',
        'hello': 'oi',
        'you': 'mate',
        'your': 'yer',
        'our': 'our',
        'we': 'we',
        'are': 'are',
        'is': 'is',
        'browse': 'take a peek',
        'look': 'check',
        'stock': 'the goods',
        'prices': 'cost',
        'marked': 'final',
        'need': 'after',
        'help': 'a favor',
        'goodbye': 'keep it quiet',
        'thanks': 'owe ya',
        'please': 'c’mon',
        'yes': 'deal',
        'no': 'pass',
        'question': 'word',
        'interested': 'in',
        'deal': 'the job',
        'trade': 'swap',
        'safe': 'no trouble',
        'come back': 'next drop',
        'see you': 'later'
    }
}
