import random

used_names = []
def generate_name() -> str:
    #this class will generate a name for crew members and ensure that only unique names are used.
   getting_name = True
   while getting_name:
    first_name = random.choice(first_names)
    last_name = random.choice(last_names)
    full_name = f'{first_name.capitalize()} {last_name.capitalize()}'
    if full_name not in used_names:
      used_names.append(full_name)
      getting_name = False
      return(full_name)

def generate_tool_modifier():
  bottom_of_range = .05
  top_of_range = .25
  generated_number = random.random()
  adjusted_number = bottom_of_range + generated_number * (top_of_range - bottom_of_range)
  return adjusted_number

first_names = [
'Aaron',
'Adam',
'Aiden',
'Alan',
'Albert',
'Alex',
'Alexander',
'Andrew',
'Anthony',
'Arthur',
'Austin',
'Benjamin',
'Blake',
'Bradley',
'Brandon',
'Brian',
'Caleb',
'Calvin',
'Cameron',
'Carl',
'Carlos',
'Charles',
'Christian',
'Christopher',
'Cody',
'Colin',
'Conor',
'Craig',
'Damian',
'Daniel',
'David',
'Dean',
'Derek',
'Dominic',
'Dylan',
'Edward',
'Elijah',
'Elliot',
'Elon',
'Eric',
'Ethan',
'Evan',
'Felix',
'Finn',
'Francis',
'Frank',
'Gabriel',
'Gary',
'George',
'Graham',
'Grant',
'Gregory',
'Harry',
'Henry',
'Isaac',
'Jack',
'Jackson',
'Jacob',
'James',
'Jason',
'Jeffrey',
'Jeremy',
'Jesse',
'Joel',
'John',
'Jonathan',
'Jordan',
'Joseph',
'Joshua',
'Julian',
'Justin',
'Keith',
'Kevin',
'Kyle',
'Lance',
'Lawrence',
'Liam',
'Logan',
'Lucas',
'Luke',
'Marcus',
'Mark',
'Martin',
'Matthew',
'Max',
'Michael',
'Nathan',
'Nicholas',
'Noah',
'Oliver',
'Oscar',
'Owen',
'Patrick',
'Paul',
'Peter',
'Philip',
'Quentin',
'Raymond',
'Richard',
'Robert',
'Ryan',
'Samuel',
'Scott',
'Sean',
'Seth',
'Shane',
'Simon',
'Spencer',
'Stephen',
'Thomas',
'Timothy',
'Toby',
'Tony',
'Travis',
'Trevor',
'Tyler',
'Vincent',
'William',
'Zachary',
'Abigail',
'Alice',
'Amelia',
'Anna',
'Aria',
'Ava',
'Bella',
'Brianna',
'Camila',
'Charlotte',
'Chloe',
'Claire',
'Daisy',
'Elizabeth',
'Ella',
'Emily',
'Emma',
'Grace',
'Hannah',
'Harper',
'Isabella',
'Isla',
'Jasmine',
'Julia',
'Kaitlyn',
'Kayla',
'Leah',
'Lila',
'Lily',
'Lucy',
'Luna',
'Melody',
'Madelyn',
'Madison',
'Maya',
'Mia',
'Natalie',
'Olivia',
'Penelope',
'Rachel',
'Rylee',
'Riley',
'Rose',
'Samantha',
'Sarah',
'Scarlett',
'Sofia',
'Sophia',
'Sophie',
'Victoria',
'Valeria',
'Violet',
'Zoe'
]

last_names = [
'Adams',
'Ahmed',
'Alvarez',
'Anderson',
'Bailey',
'Baker',
'Banerjee',
'Barnes',
'Bell',
'Bennett',
'Bhattacharya',
'Black',
'Brown',
'Burgess',
'Burns',
'Butler',
'Campbell',
'Chang',
'Chapman',
'Chen',
'Cheng',
'Chowdhury',
'Clark',
'Coleman',
'Collins',
'Cook',
'Cooper',
'Cox',
'Cruz',
'Das',
'Davies',
'Davis',
'Dean',
'Diaz',
'Dutta',
'Edwards',
'Evans',
'Fernandez',
'Fisher',
'Foster',
'Fowler',
'Fox',
'Garcia',
'Ghosh',
'Gibson',
'Gomez',
'Gonzalez',
'Gordon',
'Graham',
'Grant',
'Green',
'Gupta',
'Gutierrez',
'Hall',
'Hamilton',
'Hansen',
'Harris',
'Harrison',
'Hart',
'Hernandez',
'Hill',
'Hopkins',
'Hossain',
'Howard',
'Hughes',
'Hunter',
'Iqbal',
'Islam',
'Jackson',
'James',
'Jenkins',
'Jensen',
'Johnson',
'Jones',
'Kapoor',
'Kelly',
'Kennedy',
'Khan',
'Kim',
'King',
'Kumar',
'Kwon',
'Lee',
'Leung',
'Lewis',
'Li',
'Liang',
'Liu',
'Long',
'Lopez',
'Ma',
'Malik',
'Marshall',
'Martin',
'Martinez',
'Mason',
'Mathur',
'Matthews',
'Meyer',
'Miller',
'Mitchell',
'Mohamed',
'Moore',
'Morgan',
'Morris',
'Mukherjee',
'Murphy',
'Murray',
'Musk',
'Nagy',
'Nakamura',
'Nelson',
'Ng',
'Nguyen',
'Nishi',
'Obrien',
'Oconnor',
'Olson',
'Ortiz',
'Owen',
'Pal',
'Pandey',
'Park',
'Patel',
'Perez',
'Perry',
'Phillips',
'Powell',
'Price',
'Rahman',
'Raj',
'Ramos',
'Reed',
'Reyes',
'Reynolds',
'Richardson',
'Rivera',
'Roberts',
'Robinson',
'Rodriguez',
'Rogers',
'Ross',
'Russell',
'Sanchez',
'Sanders',
'Sarkar',
'Schmidt',
'Schneider',
'Scott',
'Shah',
'Shankar',
'Shaw',
'Shelby',
'Shen',
'Sherman',
'Singh',
'Smith',
'Snyder',
'Stark',
'Stevens',
'Stewart',
'Stone',
'Sullivan',
'Suzuki',
'Tan',
'Taylor',
'Thakur',
'Thomas',
'Thompson',
'Torres',
'Tran',
'Turner',
'Vega',
'Wagner',
'Walker',
'Wallace',
'Wang',
'Ward',
'Washington',
'Watson',
'Weber',
'West',
'White',
'Williams',
'Wilson',
'Wong',
'Wood',
'Wright',
'Wu',
'Xu',
'Yamamoto',
'Yang',
'Yi',
'Young',
'Zhang',
'Zhou',
'Zhu'
]

fish_stats = {
            'tuna': {
                    'image': []
                    ,'value': 250
                    ,'weight': 55
                    ,'rarity': 'Rare' 
                    ,'description1': 'A massive fish. Just'
                    ,'description2': '1 can feed a village.'
                }
            ,'catfish': {
                    'image': []
                    ,'value': 35
                    ,'weight': 5
                    ,'rarity': 'uncommon'
                    ,'description1': 'Large bottom feeding fish.' 
                    ,'description2':'Easier to find while still.' 
                }
            ,'salmon': {
                    'image': []
                    ,'value': 23
                    ,'weight': 3
                    ,'rarity': 'common' 
                    ,'description1': 'A treat to some groups.' 
                    ,'description2':'Prefers colder climates.'
                }
            ,'carp': {
                'image': []
                ,'value': 5
                ,'weight': 8
                ,'rarity': 'rare' 
                ,'description1':'Extremely common, carp ' 
                ,'description2':'are an invasive species.'
            }
}

crew_stats = {
    'fisherman': {
                    'name': ''
                    ,'tool_modifier': 0
                    ,'tool': 'fishing_pole'
                    ,'rarity': 'Common' 
                    ,'description1': 'Fisherman provide many'
                    ,'description2': 'options to catching fish.'
                }
}

treasure_list = {'boot': [], 'rune': [], 'metal shard': []}
crew_role_list = {'fisherman': {'selected': []
                                ,'unselected':[]}}