import random

from pygame.sprite import Sprite
from pygame.image import load
from src.utils.settings import *
from src.utils.support import import_folder
from src.utils.cameras import overlay_sprites, overlay_layers, cameragroup_layers
from src.mechanics.tools import Tool, TOOL_MAP

image_paths:str = 'assets/images/crew/tool_'

first_names:list[str] = [
    'Aaron',
    'Adam',
    'Aiden',
    'Alan',
    'Albert',
    'Alex',
    'Alexander',
    'Andrew',
    'Anthony',
    'Arthur',
    'Austin',
    'Benjamin',
    'Blake',
    'Bradley',
    'Brandon',
    'Brian',
    'Caleb',
    'Calvin',
    'Cameron',
    'Carl',
    'Carlos',
    'Charles',
    'Christian',
    'Christopher',
    'Cody',
    'Colin',
    'Conor',
    'Craig',
    'Damian',
    'Daniel',
    'David',
    'Dean',
    'Derek',
    'Dominic',
    'Dylan',
    'Edward',
    'Elijah',
    'Elliot',
    'Elon',
    'Eric',
    'Ethan',
    'Evan',
    'Felix',
    'Finn',
    'Francis',
    'Frank',
    'Gabriel',
    'Gary',
    'George',
    'Graham',
    'Grant',
    'Gregory',
    'Harry',
    'Henry',
    'Isaac',
    'Jack',
    'Jackson',
    'Jacob',
    'James',
    'Jason',
    'Jeffrey',
    'Jeremy',
    'Jesse',
    'Joel',
    'John',
    'Jonathan',
    'Jordan',
    'Joseph',
    'Joshua',
    'Julian',
    'Justin',
    'Keith',
    'Kevin',
    'Kyle',
    'Lance',
    'Lawrence',
    'Liam',
    'Logan',
    'Lucas',
    'Luke',
    'Marcus',
    'Mark',
    'Martin',
    'Matthew',
    'Max',
    'Michael',
    'Nathan',
    'Nicholas',
    'Noah',
    'Oliver',
    'Oscar',
    'Owen',
    'Patrick',
    'Paul',
    'Peter',
    'Philip',
    'Quentin',
    'Raymond',
    'Richard',
    'Robert',
    'Ryan',
    'Samuel',
    'Scott',
    'Sean',
    'Seth',
    'Shane',
    'Simon',
    'Spencer',
    'Stephen',
    'Thomas',
    'Timothy',
    'Toby',
    'Tony',
    'Travis',
    'Trevor',
    'Tyler',
    'Vincent',
    'William',
    'Zachary',
    'Abigail',
    'Alice',
    'Amelia',
    'Anna',
    'Aria',
    'Ava',
    'Bella',
    'Brianna',
    'Camila',
    'Charlotte',
    'Chloe',
    'Claire',
    'Daisy',
    'Elizabeth',
    'Ella',
    'Emily',
    'Emma',
    'Grace',
    'Hannah',
    'Harper',
    'Isabella',
    'Isla',
    'Jasmine',
    'Julia',
    'Kaitlyn',
    'Kayla',
    'Leah',
    'Lila',
    'Lily',
    'Lucy',
    'Luna',
    'Melody',
    'Madelyn',
    'Madison',
    'Maya',
    'Mia',
    'Natalie',
    'Olivia',
    'Penelope',
    'Rachel',
    'Rylee',
    'Riley',
    'Rose',
    'Samantha',
    'Sarah',
    'Scarlett',
    'Sofia',
    'Sophia',
    'Sophie',
    'Victoria',
    'Valeria',
    'Violet',
    'Zoe'
]

last_names:list[str] = [
'Adams',
'Ahmed',
'Alvarez',
'Anderson',
'Bailey',
'Baker',
'Banerjee',
'Barnes',
'Bell',
'Bennett',
'Bhattacharya',
'Black',
'Brown',
'Burgess',
'Burns',
'Butler',
'Campbell',
'Chang',
'Chapman',
'Chen',
'Cheng',
'Chowdhury',
'Clark',
'Coleman',
'Collins',
'Cook',
'Cooper',
'Cox',
'Cruz',
'Das',
'Davies',
'Davis',
'Dean',
'Diaz',
'Dutta',
'Edwards',
'Evans',
'Fernandez',
'Fisher',
'Foster',
'Fowler',
'Fox',
'Garcia',
'Ghosh',
'Gibson',
'Gomez',
'Gonzalez',
'Gordon',
'Graham',
'Grant',
'Green',
'Gupta',
'Gutierrez',
'Hall',
'Hamilton',
'Hansen',
'Harris',
'Harrison',
'Hart',
'Hernandez',
'Hill',
'Hopkins',
'Hossain',
'Howard',
'Hughes',
'Hunter',
'Iqbal',
'Islam',
'Jackson',
'James',
'Jenkins',
'Jensen',
'Johnson',
'Jones',
'Kapoor',
'Kelly',
'Kennedy',
'Khan',
'Kim',
'King',
'Kumar',
'Kwon',
'Lee',
'Leung',
'Lewis',
'Li',
'Liang',
'Liu',
'Long',
'Lopez',
'Ma',
'Malik',
'Marshall',
'Martin',
'Martinez',
'Mason',
'Mathur',
'Matthews',
'Meyer',
'Miller',
'Mitchell',
'Mohamed',
'Moore',
'Morgan',
'Morris',
'Mukherjee',
'Murphy',
'Murray',
'Musk',
'Nagy',
'Nakamura',
'Nelson',
'Ng',
'Nguyen',
'Nishi',
'Obrien',
'Oconnor',
'Olson',
'Ortiz',
'Owen',
'Pal',
'Pandey',
'Park',
'Patel',
'Perez',
'Perry',
'Phillips',
'Powell',
'Price',
'Rahman',
'Raj',
'Ramos',
'Reed',
'Reyes',
'Reynolds',
'Richardson',
'Rivera',
'Roberts',
'Robinson',
'Rodriguez',
'Rogers',
'Ross',
'Russell',
'Sanchez',
'Sanders',
'Sarkar',
'Schmidt',
'Schneider',
'Scott',
'Shah',
'Shankar',
'Shaw',
'Shelby',
'Shen',
'Sherman',
'Singh',
'Smith',
'Snyder',
'Stark',
'Stevens',
'Stewart',
'Stone',
'Sullivan',
'Suzuki',
'Tan',
'Taylor',
'Thakur',
'Thomas',
'Thompson',
'Torres',
'Tran',
'Turner',
'Vega',
'Wagner',
'Walker',
'Wallace',
'Wang',
'Ward',
'Washington',
'Watson',
'Weber',
'West',
'White',
'Williams',
'Wilson',
'Wong',
'Wood',
'Wright',
'Wu',
'Xu',
'Yamamoto',
'Yang',
'Yi',
'Young',
'Zhang',
'Zhou',
'Zhu'
]

used_names:list[str] = []

crew_roles:list[dict] = [
   {
        'role_name':'angler',
        'tool':'fishing_pole',
        'class':'fisher',
        'rarity':'Common',
        'description1': 'Use an array of rods',
        'description2': 'to catch many fish.'
    },
    {
        'role_name':'harpooner',
        'tool':'harpoon_gun',
        'class':'fisher',
        'rarity':'Uncommon',
        'description1': 'Sharpshooting fishers.',
        'description2': 'Slow, but big catches.'
    },
    {
        'role_name':'netter',
        'tool':'fishing_net',
        'class':'fisher',
        'rarity':'Rare',
        'description1': 'Netters can haul vast',
        'description2': 'quantities of sea life.'
    },
    {
        'role_name':'miner',
        'tool':'pickaxe',
        'class':'rockhound',
        'rarity':'Common',
        'description1': 'Miners pick away at',
        'description2': 'rocks to find ores.'
    },
    {
        'role_name':'powderman',
        'tool':'tnt',
        'class':'rockhound',
        'rarity':'Uncommon',
        'description1': 'Can blast apart stones',
        'description2': 'for numerous minerals.'
    },
    {
        'role_name':'quarrier',
        'tool':'stone_cutter',
        'class':'rockhound',
        'rarity':'Rare',
        'description1': 'Delicately carve out',
        'description2': 'precious gemstones.'
    },
    {
        'role_name':'quartermaster',
        'tool':'clipboard',
        'class':'deckhand',
        'rarity':'Common',
        'description1': 'Increase ship storage',
        'description2': 'capacity and effeciency.'
    },
    {
        'role_name':'helmsman',
        'tool':'oar',
        'class':'deckhand',
        'rarity':'Uncommon',
        'description1': 'Experienced sailor who',
        'description2': 'makes travel faster.'
    },
    {
        'role_name':'carpenter',
        'tool':'mallet_and_saw',
        'class':'deckhand',
        'rarity':'Rare',
        'description1': 'Upgrade and repair ',
        'description2': 'your vehicles.'
    },
    {
        'role_name':'cook',
        'tool':'cutlery',
        'class':'merchant',
        'rarity':'Common',
        'description1': 'Keep the morale high',
        'description2': 'and crewmates happy.'
    },
    {
        'role_name':'trader',
        'tool':'scale',
        'class':'merchant',
        'rarity':'Uncommon',
        'description1': 'Barter your way into',
        'description2': 'bargains and deals.'
    },
    {
        'role_name':'tailor',
        'tool':'needle_and_thread',
        'class':'merchant',
        'rarity':'Rare',
        'description1': 'Make better sails or',
        'description2': 'dress crew to the nines.'
    },
    {
        'role_name':'scavenger',
        'tool':'sea_claw',
        'class':'artificer',
        'rarity':'Common',
        'description1': 'Reach into the depths',
        'description2': 'and bring up treasure.'
    },
    {
        'role_name':'curator',
        'tool':'seer_stone',
        'class':'artificer',
        'rarity':'Uncommon',
        'description1': 'Pick through salvage',
        'description2': 'and identify treasure.'
    },
    {
        'role_name':'explorer',
        'tool':'compass',
        'class':'artificer',
        'rarity':'Rare',
        'description1': 'Effortlessley navigate',
        'description2': 'environmental phenomenon.'
    },
    {
        'role_name':'distiller',
        'tool':'tap',
        'class':'islander',
        'rarity':'Rare',
        'description1': 'Produce barrels of',
        'description2': 'valuable liquids.'
    },
    {
        'role_name':'farmer',
        'tool':'shovel_and_pail',
        'class':'islander',
        'rarity':'Rare',
        'description1': 'Grow myriad of crops',
        'description2': 'for a variety of uses.'
    },
    {
        'role_name':'hunter',
        'tool':'spear',
        'class':'islander',
        'rarity':'Rare',
        'description1': 'Hunt, slaughter, and',
        'description2': 'herd all the animals.'
    },
    {
        'role_name':'spy',
        'tool':'lockpick',
        'class':'operative',
        'rarity':'Rare',
        'description1': 'Steal shop items',
        'description2': 'and decieve crew.'
    },
    {
        'role_name':'cartographer',
        'tool':'map',
        'class':'operative',
        'rarity':'Common',
        'description1': 'Create and read maps.',
        'description2': "You'll never get lost."
    },
    {
        'role_name':'scholar',
        'tool':'book_and_quill',
        'class':'operative',
        'rarity':'Uncommon',
        'description1': 'Highly knowledgable,',
        'description2': 'improve other crew.'
    }
]

role_vocabularies:dict[str, dict] = {
    'fisher': {
        'stock': 'bait and tackle',
        'wares': 'nets and hooks',
        'inventory': 'fishing gear',
        'browse': 'check the nets',
        'look': 'eye the traps',
        'examine': 'inspect the lines',
        'need': 'hookin',
        'require': 'baitin',
        'help': 'a cast',
        'assistance': 'a line',
        'interesting': 'big one',
        'prime': 'monster catch',
        'rare': 'legendary',
        'place': 'fishin hole',
        'market': 'best tide',
        'area': 'deep drop',
        'work': 'haulin nets',
        'working': 'castin lines',
        'trade': 'swap catches',
        'deal': 'fresh haul',
        'cargo': 'barrels of fish',
        'provisions': 'salted cod',
        'safe': 'no sharks',
        'come back': 'when the tide’s right',
        'see you': 'next full moon',
        'water': 'brine',
        'sea': 'the drink',
        'storm': 'blow',
        'wind': 'breeze off the reef',
        'island': 'atoll',
        'ship': 'skiff',
        'crew': 'deckhand',
        'you': 'cap’n',
        'we': 'the crew'
    },
    'rockhound': {
        'stock': 'picks and chisels',
        'wares': 'ore samples',
        'inventory': 'raw gems',
        'browse': 'sort the stones',
        'look': 'scan the haul',
        'examine': 'grade the rocks',
        'need': 'diggin',
        'require': 'blastin',
        'help': 'a vein',
        'assistance': 'a strike',
        'interesting': 'motherlode',
        'prime': 'high-grade seam',
        'rare': 'blood diamond',
        'place': 'quarry face',
        'market': 'refinery',
        'area': 'crater ridge',
        'work': 'breakin rock',
        'working': 'hammerin stone',
        'trade': 'swap nuggets',
        'deal': 'raw ore',
        'cargo': 'sacks of quartz',
        'provisions': 'lantern oil',
        'safe': 'no cave-ins',
        'come back': 'after the next blast',
        'see you': 'when the dust settles',
        'water': 'underground spring',
        'sea': 'dry dock',
        'storm': 'rockslide',
        'wind': 'tunnel draft',
        'island': 'volcanic peak',
        'ship': 'cargo hauler',
        'crew': 'miner',
        'you': 'foreman',
        'we': 'the crew'
    },
    'deckhand': {
        'stock': 'oars and tholes',
        'wares': 'sweat and muscle',
        'inventory': 'spare benches',
        'browse': 'check the stroke',
        'look': 'time the pull',
        'examine': 'feel the rhythm',
        'need': 'pullin',
        'require': 'rowin hard',
        'help': 'a stroke',
        'assistance': 'a beat',
        'interesting': 'strong current',
        'prime': 'tailwind run',
        'rare': 'perfect cadence',
        'place': 'open lane',
        'market': 'finish line',
        'area': 'smooth water',
        'work': 'haulin oar',
        'working': 'keepin time',
        'trade': 'swap shifts',
        'deal': 'faster passage',
        'cargo': 'light load',
        'provisions': 'water skins',
        'safe': 'no blisters',
        'come back': 'at the next tide',
        'see you': 'on the downbeat',
        'water': 'channel',
        'sea': 'the race',
        'storm': 'headwind',
        'wind': 'following breeze',
        'island': 'lee shore',
        'ship': 'longboat',
        'crew': 'rower',
        'you': 'coxswain',
        'we': 'the bench'
    },
    'merchant': {
        'stock': 'cargo manifest',
        'wares': 'trade goods',
        'inventory': 'market rates',
        'browse': 'review the ledger',
        'look': 'check the margins',
        'examine': 'audit the books',
        'need': 'negotiate',
        'require': 'counter-offer',
        'help': 'a bargain',
        'assistance': 'a deal',
        'interesting': 'hot commodity',
        'prime': 'bull market',
        'rare': 'exclusive contract',
        'place': 'best market',
        'market': 'trading post',
        'area': 'port of call',
        'work': 'makin deals',
        'working': 'closing sales',
        'trade': 'barter',
        'deal': 'final price',
        'cargo': 'hold full',
        'provisions': 'luxury items',
        'safe': 'no tariffs',
        'come back': 'when prices rise',
        'see you': 'at the exchange',
        'water': 'shipping lane',
        'sea': 'trade winds',
        'storm': 'market crash',
        'wind': 'favorable rates',
        'island': 'free port',
        'ship': 'merchantman',
        'crew': 'factor',
        'you': 'buyer',
        'we': 'the house'
    },
    'artificer': {
        'stock': 'bandages and salves',
        'wares': 'herbs and rum',
        'inventory': 'medical kit',
        'browse': 'check the wounds',
        'look': 'take a pulse',
        'examine': 'diagnose',
        'need': 'stitchin',
        'require': 'amputatin',
        'help': 'a poultice',
        'assistance': 'a dose',
        'interesting': 'plague outbreak',
        'prime': 'miracle cure',
        'rare': 'fountain herb',
        'place': 'sick bay',
        'market': 'apothecary',
        'area': 'below deck',
        'work': 'tendin wounds',
        'working': 'boilin instruments',
        'trade': 'swap remedies',
        'deal': 'health contract',
        'cargo': 'medical crates',
        'provisions': 'laudanum',
        'safe': 'no infection',
        'come back': 'after the fever breaks',
        'see you': 'when you’re whole',
        'water': 'blood',
        'sea': 'the fever',
        'storm': 'outbreak',
        'wind': 'plague wind',
        'island': 'leper colony',
        'ship': 'hospital ship',
        'crew': 'patient',
        'you': 'captain',
        'we': 'the orderlies'
    },
    'islander': {
        'stock': 'casks and barrels',
        'wares': 'pressings and oils',
        'inventory': 'fermenting vats',
        'browse': 'check the casks',
        'look': 'eye the barrels',
        'examine': 'inspect the press',
        'need': 'tapin',
        'require': 'fermentin',
        'help': 'a draw',
        'assistance': 'a stir',
        'interesting': 'prime vintage',
        'prime': 'rare extract',
        'rare': 'legendary batch',
        'place': 'distillery',
        'market': 'trading post',
        'area': 'vineyard row',
        'work': 'pressin grapes',
        'working': 'stirrin vats',
        'trade': 'swap barrels',
        'deal': 'finished product',
        'cargo': 'kegs and casks',
        'provisions': 'clean water',
        'safe': 'no spills',
        'come back': 'after fermentation',
        'see you': 'at the next harvest',
        'water': 'clear draught',
        'sea': 'the vat',
        'storm': 'overflow',
        'wind': 'fermenting breeze',
        'island': 'vine-covered hill',
        'ship': 'press house',
        'crew': 'islander',
        'you': 'master of casks',
        'we': 'the cellar crew'
    },
    'operative': {
        'stock': 'coded messages',
        'wares': 'intel and secrets',
        'inventory': 'disguises and notes',
        'browse': 'review the reports',
        'look': 'observe the targets',
        'examine': 'scrutinize the situation',
        'need': 'gather info',
        'require': 'tail the mark',
        'help': 'a tip',
        'assistance': 'a lead',
        'interesting': 'suspicious activity',
        'prime': 'critical intel',
        'rare': 'classified info',
        'place': 'safe house',
        'market': 'informant network',
        'area': 'operating zone',
        'work': 'collect intelligence',
        'working': 'shadowing the target',
        'trade': 'exchange tips',
        'deal': 'covert arrangement',
        'cargo': 'secret parcels',
        'provisions': 'hidden supplies',
        'safe': 'undetected',
        'come back': 'after recon',
        'see you': 'at the rendezvous',
        'water': 'channels and couriers',
        'sea': 'information network',
        'storm': 'crisis',
        'wind': 'whispers',
        'island': 'hideout',
        'ship': 'disguised conveyance',
        'crew': 'operative',
        'you': 'handler',
        'we': 'the cell'
    },
}

archetype_vocabularies:dict[str, dict] = {
    'pirate': {
        'welcome': 'ahoy',
        'hello': 'ahoy',
        'you': 'ye',
        'your': 'yer',
        'our': 'me',
        'are': 'be',
        'is': 'be',
        'browse': 'eyeball',
        'look': 'gander',
        'stock': 'wares',
        'prices': 'prices',
        'marked': 'carved in stone',
        'need': 'be needin',
        'help': 'lend a hand',
        'goodbye': 'fare thee well',
        'thanks': 'much obliged',
        'please': 'if ye please',
        'yes': 'aye',
        'no': 'nay',
        'question': 'query',
        'interested': 'keen',
        'deal': 'bargain',
        'trade': 'swap',
        'safe': 'fair winds',
        'come back': 'return to port',
        'see you': 'catch ye on the tide'
    },
    'colonial': {
        'welcome': 'good day',
        'hello': 'greetings',
        'you': 'sir',
        'your': 'your',
        'our': 'our',
        'we': 'we',
        'are': 'are',
        'is': 'is',
        'browse': 'peruse',
        'look': 'examine',
        'stock': 'inventory',
        'prices': 'rates',
        'marked': 'listed',
        'need': 'require',
        'help': 'assistance',
        'goodbye': 'farewell',
        'thanks': 'my thanks',
        'please': 'if you please',
        'yes': 'indeed',
        'no': 'I decline',
        'question': 'inquiry',
        'interested': 'intrigued',
        'deal': 'arrangement',
        'trade': 'commerce',
        'safe': 'godspeed',
        'come back': 'return at your leisure',
        'see you': 'until we meet again'
    },
    'smuggler': {
        'welcome': 'psst',
        'hello': 'oi',
        'you': 'mate',
        'your': 'yer',
        'our': 'our',
        'we': 'we',
        'are': 'are',
        'is': 'is',
        'browse': 'take a peek',
        'look': 'check',
        'stock': 'the goods',
        'prices': 'cost',
        'marked': 'final',
        'need': 'after',
        'help': 'a favor',
        'goodbye': 'keep it quiet',
        'thanks': 'owe ya',
        'please': 'c’mon',
        'yes': 'deal',
        'no': 'pass',
        'question': 'word',
        'interested': 'in',
        'deal': 'the job',
        'trade': 'swap',
        'safe': 'no trouble',
        'come back': 'next drop',
        'see you': 'later'
    }
}

def generate_name() -> str:
    #this class will generate a name for crew members and ensure that only unique names are used.
   getting_name = True
   while getting_name:
    first_name = random.choice(first_names)
    last_name = random.choice(last_names)
    full_name = f'{first_name.capitalize()} {last_name.capitalize()}'
    if full_name not in used_names:
      used_names.append(full_name)
      getting_name = False
      return(full_name)


class CrewSprite(Sprite):
    def __init__(self, tool_name:str, master) -> None:
       super().__init__(overlay_sprites)
       self.image = load(image_paths + tool_name + '.png').convert_alpha()
       self.rect = self.image.get_rect()
       self.z=overlay_layers['menu_items']
       self.master = master
       
    def update(self, *args, **kwargs) -> None:
       self.master.update()
       #lets make a group called an update group to avoid this up chain calling
       #children shoulnd't control parents

class Crew:
    def __init__(self, role_attrs:dict[str, str]):
        """
        A Crew will contain an tool used for finding items or performing in game mechanics based on its role.

        Parameters
        - sprite_group: Overlay camera Group

        - crew_role : str
            Name of the role that the class will perform. Determines what tools can be used.

        - owner: 
            Sprite sub-class such as an NPC or the player

        - z : int 
            Drawing layer
        """
        self.role_name:str = role_attrs.get('role_name')
        self.name = generate_name()
        self.tool:Tool = TOOL_MAP[role_attrs.get('tool')](self)
        self.class_type = role_attrs.get('class')
        self.rarity = role_attrs.get('rarity')
        self.description = [role_attrs.get('description1'), role_attrs.get('description2')]
        self.archetype = random.choice(list(archetype_vocabularies.keys()))
        self.sprite = CrewSprite(role_attrs.get('tool'), self)
        overlay_sprites.remove(self.sprite)
        self.master = None
        self.selected:bool = False
        self._init_skills()

    def _init_skills(self) -> None:
        self.tool_use_rate:int = 0
        self.tool_effeciency_modifier:int = 0
        self.max_health:int = 50
        self.max_hydration:int = 50
        self.max_morale:int = 50
        self.health:int = self.max_health
        self.hydration:int = self.max_hydration
        self.morale:int = self.max_morale
        self.skills:list[int] = [
           self.tool_use_rate,
           self.tool_effeciency_modifier,
           self.max_health,
           self.max_hydration,
           self.max_morale
        ]

    def set_master(self, master) -> None:
       self.master = master

    def _select(self) -> None:
        self.selected = True

    def deselect(self) -> None:
       self.selected = False

    def update(self, *args, **kwargs) -> None:
       if self.selected:
          self.tool.use()

    def toggle_selected(self) -> None:
        if self.selected:
            self.deselect()
        else:
            self._select()


def build_crew_member(owner, role_name) -> Crew:
   for role in crew_roles:
      if role_name == role.get('role_name'):
        crew_member = Crew(role)
        crew_member.set_master(owner)
        return crew_member